# Site settings
title: Gabriel L&#243pez-Moctezuma
email: glmoctezuma@gmail.com
description: Academic Website of Gabriel L&#243pez-Moctezuma
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  glmoctezuma

gems:
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# Other options
jobtitle: Postdoctoral Research Fellow
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# SEO stuff
#google_author: "a"
# google_site_verification: ""
# bing_webmastertools_id: ""