# Site settings
title: Gabriel L&#243pez-Moctezuma
email: glmoctezuma@gmail.com
description: Academic Website of Gabriel L&#243pez-Moctezuma
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  glmoctezuma

gems:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Build settings
markdown: kramdown

# Other options
jobtitle: Postdoctoral Research Fellow
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# Google services
google_analytics: UA-84011332-1

# SEO stuff
#google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""